### ISSUE TITLE
IGR controller commands don't work when region detection tripped (with no d4 patch) 

### ISSUE THREAD

**Issue by BadAd84** [borti4938/Switchless-Mods#4]
If I boot a game that is ntsc but the console is in PAL(50hz) mode and the game is one that has the region detection, it sits at the region lockout screen and I can't change the mode or reset the console from the controller. If i boot in ntsc everything works fine, as does switching to pal (and all button combinations work while in pal mode) but I have to do this from the reset button on the console.

**Comment by borti4938** [comment]
It depends on the game you actually running.
The uIGR is a passive reader of the controller protocol; the PIC does not read the controller by itself. So as long as the S-CPU does not read the controller, the uIGR never respond on button combinations (because the bits are not sent).
Situations where the SNES does not read the controller could be intros, producer/publisher screens, region lock screens, and so on.
This means, if the programm stop controller reading while entering the region lock screen, it seems that the uIGR does not respond on the controller anymore. E.g. I know that Sunset Riders continues reading the controller during the lock screen, others don't. However, changing the region using the reset button should work.
In general, I recommend to activate the region timeout if no region patch is installed. This holds the console in the by the SuperCIC detected cartrdige region for 9s after powering on or resetting the console. (During that time the uIGR runs a loop where the PIC neither responds on button combinations nor on the reset button)

**Comment by BadAd84** [comment]
So would the new version you uploaded recently for me be in the region timeout mode always on start up (like what is forced when you set it via the supercic pin 4 connected to vcc?) regardless of the stored state in the uIGR?

**Comment by borti4938** [comment]
Could you please confirm that the uIGR is able to forward the SuperCIC region change while the SNES stucks in the region lock screen of the particular game you tested? (as I expect)
If the uIGR does not react, this is in deed a bug.

**Comment by BadAd84** [comment]
You mean via the reset button? If so, that is already confirmed - I edited my original comment to include this information.

**Comment by BadAd84** [comment]
I see your edit.

I will use this version until my D4 patch board is ready. I had just used the default version(s) as I did a manual fix on pin 4 to ground

**Comment by borti4938** [comment]
Yes, I mean changing the mode via the reset button. Then the uIGR works as expected :)
